//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clases
    {
        public int id_clases { get; set; }
        public System.DateTime fecha { get; set; }
        public string cliente_clases { get; set; }
        public System.TimeSpan hora_inicio { get; set; }
        public System.TimeSpan hora_final { get; set; }
        public int contrato_clases { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual contratos contratos { get; set; }
    }
}
