//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagos
    {
        public int id_pagos { get; set; }
        public System.DateTime fecha_pago { get; set; }
        public int nombre_pago { get; set; }
        public string cliente_pago { get; set; }
        public int monto { get; set; }
        public int contrato_servicio { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual contratos contratos { get; set; }
        public virtual tipo_pago tipo_pago { get; set; }
    }
}
